SELECT l.TAG_ID, t.TAG_NAME, o.OBJECT_TYPE, ot.OBJECT_DESC, o.OBJECT_NO, o.OBJECT_NAME, l.ALARM_STATE, l.ALARM_VALUE, l.ALARM_SET_TIME, 
NVL(l.ALARM_CLR_TIME, CURRENT_DATE) AS ALARM_CLR_TIME FROM SC_TAG t
JOIN SC_ALARM_LOG l ON l.TAG_ID = t.TAG_ID
JOIN OBJECT o ON o.OBJECT_NO = t.OBJECT_NO
JOIN OBJECT_TYPE ot on o.OBJECT_TYPE = ot.OBJECT_TYPE
WHERE l.TAG_ID IN (SELECT TAG_ID FROM SC_TAG WHERE TAG_NAME LIKE 'G%_OOS')
/* AND ot.OBJECT_DESC IN ('REGULATOR', 'HYBRID_R', 'OFFTAKE', 'SLIPMETER R', 'SLIPGATE R', 'FLUMEGATE R', 'MULTIGATE_R',  'BLADEMETER R') */