select distinct o.object_no from object o
JOIN OBJECT_TYPE ot on o.OBJECT_TYPE = ot.OBJECT_TYPE
WHERE
(ot.OBJECT_DESC IN ('REGULATOR', 'HYBRID_R', 'OFFTAKE', 'SLIPMETER R', 'SLIPGATE R', 'FLUMEGATE R', 'MULTIGATE_R', 'BLADEMETER R', 'BRIDGE'))

