SELECT distinct o.OBJECT_NO, o.OBJECT_NAME, ot.OBJECT_DESC FROM SC_TAG t
              join OBJECT o on t.OBJECT_NO = o.OBJECT_NO
              JOIN OBJECT_TYPE ot on o.OBJECT_TYPE = ot.OBJECT_TYPE
              WHERE TAG_NAME LIKE 'G%_OOS' AND t.OBJECT_NO IS NOT NULL
              /* AND ot.OBJECT_DESC IN ('REGULATOR', 'HYBRID_R', 'OFFTAKE', 'SLIPMETER R', 'SLIPGATE R', 'FLUMEGATE R', 'MULTIGATE_R',  'BLADEMETER R') */
