SELECT  o.OBJECT_NO, o.OBJECT_NAME, ot.OBJECT_DESC, t.TAG_NAME, t.TAG_DESC, t.TAG_VALUE, t.TAG_TIME, c.CAPTION_CODE_DESC as RADIO_LINE, 

    CASE 
        WHEN t.TAG_VALUE < 4 THEN 'MOSCAD'
        WHEN t.TAG_VALUE >= 5 THEN 'ACE1000'
        ELSE 'OTHER'
    END ACE_MOSCAD
    
    FROM SC_TAG t
    LEFT JOIN SC_CAPTION_CODE c ON c.CAPTION_ID = t.CAPTION_ID AND t.TAG_VALUE = c.CAPTION_CODE_VALUE
    JOIN OBJECT o ON o.OBJECT_NO = t.OBJECT_NO
    JOIN OBJECT_TYPE ot ON ot.OBJECT_TYPE = o.OBJECT_TYPE
    WHERE t.TAG_NAME IN ('SDB_VER', 'RTU_PORT3_LINK_ID', 'RTU_LINK_ID', 'RTU_SW_VER_NO', 'RTU_CODESYS_SW_VER_NO', 'ISOFTWARE_VERSION', 'USL1_SENS_VER')